import { Download, FileText } from "lucide-react";

import { reports } from "../../data/dashboard";

export default function RecentReports() {
  return (
    <section
      className="
        rounded-3xl

        border
        border-slate-200
        dark:border-slate-800

        bg-white
        dark:bg-slate-900

        p-6
      "
    >
      {/* Header */}

      <div className="mb-6">
        <h2 className="text-xl font-bold text-slate-900 dark:text-white">
          Recent Reports
        </h2>

        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
          Executive reports generated by InsightIQ.
        </p>
      </div>

      {/* Report List */}

      <div className="space-y-4">
        {reports.map((report) => (
          <div
            key={report.id}
            className="
              group

              flex
              items-center
              justify-between

              rounded-2xl

              border
              border-slate-200
              dark:border-slate-800

              bg-slate-50
              dark:bg-slate-950/60

              p-4

              transition-all
              duration-300

              hover:border-blue-500/30
              hover:bg-blue-50/40
              dark:hover:bg-slate-800
            "
          >
            <div className="flex items-center gap-4">

              <div
                className="
                  flex
                  h-12
                  w-12
                  items-center
                  justify-center

                  rounded-xl

                  bg-indigo-500/10

                  text-indigo-600
                  dark:text-indigo-400
                "
              >
                <FileText size={22} />
              </div>

              <div>
                <h3 className="font-semibold text-slate-900 dark:text-white">
                  {report.title}
                </h3>

                <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
                  Generated {report.date}
                </p>
              </div>

            </div>

            <button
              className="
                flex
                h-11
                w-11
                items-center
                justify-center

                rounded-xl

                border
                border-slate-200
                dark:border-slate-700

                transition-all

                hover:border-blue-500
                hover:bg-blue-500
                hover:text-white
              "
            >
              <Download
                size={18}
                className="transition-transform group-hover:scale-110"
              />
            </button>
          </div>
        ))}
      </div>

      {/* Footer */}

      <div className="mt-6 border-t border-slate-200 pt-4 dark:border-slate-800">

        <p className="text-sm text-slate-500 dark:text-slate-400">
          Reports can be exported as PDF or Excel for sharing with your team.
        </p>

      </div>
    </section>
  );
}